// web/ui/src/pages/components/XaiAccountCard.tsx
import type { XaiAccount, XaiQuotaWindow } from '@/types'
import { getXaiExpireInfo, getXaiStatus } from '@/lib/xai'
import { ActivityIcon, CopyIcon, EditIcon, GaugeIcon, PowerIcon, RefreshIcon, TrashIcon } from '@/components/icons'

interface XaiAccountCardProps {
  account: XaiAccount
  busyAction: string
  onActivate: (accountId: string) => void
  onProbeStream: (accountId: string) => void
  onRefreshQuota: (accountId: string) => void
  onRefreshToken: (accountId: string) => void
  onCopy: (account: XaiAccount) => void
  onEdit: (account: XaiAccount) => void
  onDelete: (accountId: string) => void
}

function poolLabel(pool?: string): string {
  switch (String(pool || '').toLowerCase()) {
    case 'super':
      return 'Super'
    case 'heavy':
      return 'Heavy'
    case 'basic':
      return 'Basic'
    default:
      // 空 pool 与后端 console 一致，视为 Basic
      return 'Basic'
  }
}

function formatQuotaPart(label: string, win?: XaiQuotaWindow): string {
  if (!win || win.total == null || win.total <= 0) return ''
  const remaining = Math.max(0, Number(win.remaining ?? 0))
  return `${label} ${remaining}/${win.total}`
}

function quotaSummary(account: XaiAccount): string {
  const q = account.quota
  if (!q) return ''
  return [
    formatQuotaPart('Fast', q.fast),
    formatQuotaPart('Auto', q.auto),
    formatQuotaPart('Expert', q.expert),
    formatQuotaPart('Heavy', q.heavy),
  ]
    .filter(Boolean)
    .join(' · ')
}

export default function XaiAccountCard({
  account,
  busyAction,
  onActivate,
  onProbeStream,
  onRefreshQuota,
  onRefreshToken,
  onCopy,
  onEdit,
  onDelete,
}: XaiAccountCardProps) {
  const status = getXaiStatus(account)
  const displayName = account.email || account.subject || account.id || '(未命名账号)'
  const localId = account.id || ''
  const canActivate = Boolean(localId) && !account.isActive && account.status !== 'banned'
  const canRefreshQuota = Boolean(String(account.sso || '').trim())
  const activateBusy = busyAction === `xai:activate:${localId}`
  const probeBusy = busyAction === `xai:probe:${localId}`
  const quotaBusy = busyAction === `xai:quota:${localId}`
  const refreshBusy = busyAction === `xai:refresh:${localId}`
  const deleteBusy = busyAction === `xai:delete:${localId}`
  const actionBusy = activateBusy || probeBusy || quotaBusy || refreshBusy || deleteBusy
  const pool = poolLabel(account.pool)
  const quotaText = quotaSummary(account)

  const expireInfo = getXaiExpireInfo(account)

  return (
    <article className={`codex-account-card xai-account-card${account.isActive ? ' active' : ''}`}>
      <div className="codex-account-card-header">
        <div className="codex-header-main">
          <h3 className="list-item-title no-margin codex-card-title" title={displayName}>
            {displayName}
          </h3>
          <span className={`badge ${status.variant}`}>{status.label}</span>
        </div>

        <div className="codex-card-tags">
          {pool ? <span className="badge info">{pool}</span> : null}
          {account.authKind === 'api_key' ? <span className="badge info">API Key</span> : null}
          {account.enabled === false ? <span className="badge danger">已禁用</span> : null}
          {account.websockets ? <span className="badge success">WS</span> : null}
          {account.usingApi ? <span className="badge warning">官方API</span> : null}
          {String(account.sso || '').trim() ? <span className="badge info">SSO</span> : null}
          {account.isActive ? <span className="badge success">正在使用</span> : null}
        </div>
      </div>

      {quotaText || account.proxyUrl ? (
        <div className="codex-account-card-body">
          <div className="codex-account-meta-grid">
            {quotaText ? <div className="meta-pill codex-full-span">{quotaText}</div> : null}
            {account.proxyUrl ? <div className="meta-pill codex-full-span">代理：{account.proxyUrl}</div> : null}
          </div>
        </div>
      ) : null}

      <div className="codex-account-card-footer">
        <div
          className={`codex-expire-text${expireInfo.expired ? ' danger-text' : ''}`}
          title={account.expiresAt || undefined}
        >
          {expireInfo.text}
        </div>

        <div className="codex-card-actions">
          {canActivate ? (
            <button
              className="codex-action-btn codex-action-primary"
              type="button"
              title={activateBusy ? '激活中...' : '激活'}
              aria-label="激活"
              disabled={actionBusy}
              onClick={() => onActivate(localId)}
            >
              <PowerIcon />
            </button>
          ) : null}
          <button
            className="codex-action-btn"
            type="button"
            title={probeBusy ? '连通测试中...' : '连通测试'}
            aria-label="连通测试"
            disabled={actionBusy || !localId}
            onClick={() => onProbeStream(localId)}
          >
            <ActivityIcon />
          </button>
          <button
            className="codex-action-btn"
            type="button"
            title={
              !canRefreshQuota
                ? '需要 SSO Cookie 才能刷新额度'
                : quotaBusy
                  ? '刷新额度中...'
                  : '刷新额度'
            }
            aria-label="刷新额度"
            disabled={actionBusy || !localId || !canRefreshQuota}
            onClick={() => onRefreshQuota(localId)}
          >
            <GaugeIcon />
          </button>
          <button
            className="codex-action-btn"
            type="button"
            title={refreshBusy ? '刷新 Token 中...' : '刷新 Token'}
            aria-label="刷新 Token"
            disabled={actionBusy || !localId}
            onClick={() => onRefreshToken(localId)}
          >
            <RefreshIcon />
          </button>
          <button
            className="codex-action-btn"
            type="button"
            title="复制 auth.json"
            aria-label="复制"
            disabled={actionBusy}
            onClick={() => onCopy(account)}
          >
            <CopyIcon />
          </button>
          <button
            className="codex-action-btn"
            type="button"
            title="编辑"
            aria-label="编辑"
            disabled={actionBusy}
            onClick={() => onEdit(account)}
          >
            <EditIcon />
          </button>
          <button
            className="codex-action-btn codex-action-danger"
            type="button"
            title={deleteBusy ? '删除中...' : '删除'}
            aria-label="删除"
            disabled={actionBusy || !localId}
            onClick={() => {
              if (window.confirm(`确定删除 xAI 账号 ${displayName} 吗？`)) {
                onDelete(localId)
              }
            }}
          >
            <TrashIcon />
          </button>
        </div>
      </div>
    </article>
  )
}

// desktop/ui/src/components/xai/XaiAccountCard.vue
<template>
  <div
    class="xai-account-card"
    :class="{
      active: isActive,
      banned: isBanned,
      cooldown: isCoolingDown
    }"
  >
    <div class="xai-card-header">
      <span class="account-email" :title="displayName">{{ displayName }}</span>
      <n-tag :type="statusType" size="small" round>{{ statusText }}</n-tag>
    </div>

    <div class="card-tags">
      <n-tag v-if="poolLabel" type="info" size="small">
        {{ poolLabel }}
      </n-tag>
      <n-tag v-if="account.authKind === 'api_key'" type="info" size="small">
        {{ t('xai.authApiKey') }}
      </n-tag>
      <n-tag v-if="account.enabled === false" type="error" size="small">
        {{ t('xai.disabledLabel') }}
      </n-tag>
      <n-tag v-if="account.websockets" type="success" size="small">
        WS
      </n-tag>
      <n-tag v-if="account.usingApi" type="warning" size="small">
        {{ t('xai.usingApiBadge') }}
      </n-tag>
      <n-tag v-if="account.sso" type="info" size="small">
        SSO
      </n-tag>
      <n-tag v-if="isActive" size="tiny" type="success" round class="xai-badge-active">
        {{ t('xai.active') }}
      </n-tag>
    </div>

    <div v-if="quotaSummary || account.proxyUrl" class="card-body">
      <div v-if="quotaSummary" class="quota-info" :title="quotaSummary">
        {{ quotaSummary }}
      </div>
      <div v-if="account.proxyUrl" class="proxy-info">
        {{ t('xai.proxy') }}: {{ truncateText(account.proxyUrl, 30) }}
      </div>
    </div>

    <div class="card-footer">
      <div class="expire-info" :class="{ expired: isExpired }">
        {{ expireText }}
      </div>
      <div class="card-actions">
        <button
          v-if="canActivate"
          type="button"
          class="xai-action-btn xai-action-primary"
          :title="t('xai.activate')"
          :aria-label="t('xai.activate')"
          :disabled="busy"
          @click="emit('activate', account.id || '')"
        >
          <Power class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn"
          :title="t('xai.probeStream')"
          :aria-label="t('xai.probeStream')"
          :disabled="busy"
          @click="emit('test', account.id || '')"
        >
          <Activity class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn"
          :title="t('xai.refreshQuota')"
          :aria-label="t('xai.refreshQuota')"
          :disabled="busy || !canRefreshQuota"
          @click="emit('refresh-quota', account.id || '')"
        >
          <Gauge class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn"
          :title="t('xai.test')"
          :aria-label="t('xai.test')"
          :disabled="busy"
          @click="emit('refresh-token', account.id || '')"
        >
          <RefreshCw class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn"
          :title="t('xai.copy')"
          :aria-label="t('xai.copy')"
          :disabled="busy"
          @click="emit('copy', account)"
        >
          <Copy class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn"
          :title="t('xai.edit')"
          :aria-label="t('xai.edit')"
          :disabled="busy"
          @click="emit('edit', account)"
        >
          <Edit class="xai-action-icon" />
        </button>
        <button
          type="button"
          class="xai-action-btn xai-action-danger"
          :title="t('common.delete')"
          :aria-label="t('common.delete')"
          :disabled="busy"
          @click="confirmDelete"
        >
          <Trash class="xai-action-icon" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onBeforeUnmount } from 'vue'
import { NTag, useDialog } from 'naive-ui'
import { Power, RefreshCw, Copy, Edit, Trash, Activity, Gauge } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import type { XaiAccount, XaiQuotaWindow } from '@/types/xai'

const { t } = useI18n()
const dialog = useDialog()

const props = withDefaults(defineProps<{
  account: XaiAccount
  isActive?: boolean
  busy?: boolean
}>(), {
  isActive: false,
  busy: false
})

const emit = defineEmits<{
  activate: [accountId: string]
  test: [accountId: string]
  'refresh-quota': [accountId: string]
  'refresh-token': [accountId: string]
  copy: [account: XaiAccount]
  edit: [account: XaiAccount]
  delete: [accountId: string]
}>()

const isCoolingDown = computed(() => (props.account.cooldownRemaining || 0) > 0)
const isBanned = computed(() => props.account.status === 'banned')
const nowTick = ref(Date.now())
let expireTickTimer: ReturnType<typeof setInterval> | null = null

const displayName = computed(() =>
  props.account.email || props.account.subject || props.account.id || truncateToken(props.account.refreshToken || props.account.apiKey)
)

const statusType = computed<'default' | 'success' | 'warning' | 'error'>(() => {
  if (isCoolingDown.value) return 'warning'
  switch (props.account.status) {
    case 'valid': return 'success'
    case 'banned': return 'error'
    case 'exhausted': return 'warning'
    default: return 'default'
  }
})

const statusText = computed(() => {
  if (isCoolingDown.value) return cooldownText.value
  switch (props.account.status) {
    case 'valid': return t('xai.statusValid')
    case 'banned': return t('xai.statusBanned')
    case 'exhausted': return t('xai.statusExhausted')
    default: return t('xai.statusUnknown')
  }
})

const cooldownText = computed(() => {
  const remaining = props.account.cooldownRemaining
  if (!remaining || remaining <= 0) return ''
  const label = t('xai.cooling')
  if (remaining < 60) {
    return `${label} ${remaining}s`
  }
  const mins = Math.ceil(remaining / 60)
  if (mins >= 60) {
    const h = Math.floor(mins / 60)
    const m = mins % 60
    return `${label} ${h}h${m > 0 ? m + 'm' : ''}`
  }
  return `${label} ${mins}m`
})

const expireInfo = computed(() => {
  void nowTick.value
  if (!props.account.expiresAt) return { text: '', isExpired: false }
  const expiresDate = new Date(props.account.expiresAt)
  const now = new Date(nowTick.value)
  if (isNaN(expiresDate.getTime())) return { text: '', isExpired: false }
  const diffMs = expiresDate.getTime() - now.getTime()
  if (diffMs <= 0) return { text: t('xai.tokenExpired'), isExpired: true }
  const diffMinutes = Math.floor(diffMs / (1000 * 60))
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60))
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
  if (diffDays > 0) return { text: `${diffDays}d`, isExpired: false }
  if (diffHours > 0) return { text: `${diffHours}h`, isExpired: false }
  return { text: `${diffMinutes}m`, isExpired: false }
})

const expireText = computed(() => (expireInfo.value.text ? expireInfo.value.text : ''))
const isExpired = computed(() => expireInfo.value.isExpired)
const canActivate = computed(() => !props.isActive && props.account.status !== 'banned')
const canRefreshQuota = computed(() => Boolean(String(props.account.sso || '').trim()))

const poolLabel = computed(() => {
  switch (String(props.account.pool || '').toLowerCase()) {
    case 'super':
      return t('xai.poolSuper')
    case 'heavy':
      return t('xai.poolHeavy')
    case 'basic':
      return t('xai.poolBasic')
    default:
      // 空 pool 与后端 console 一致，视为 Basic
      return t('xai.poolBasic')
  }
})

function formatQuotaPart(label: string, win?: XaiQuotaWindow): string {
  if (!win || win.total == null || win.total <= 0) return ''
  const remaining = Math.max(0, Number(win.remaining ?? 0))
  return `${label} ${remaining}/${win.total}`
}

const quotaSummary = computed(() => {
  const q = props.account.quota
  if (!q) return ''
  const parts = [
    formatQuotaPart(t('xai.quotaFast'), q.fast),
    formatQuotaPart(t('xai.quotaAuto'), q.auto),
    formatQuotaPart(t('xai.quotaExpert'), q.expert),
    formatQuotaPart(t('xai.quotaHeavy'), q.heavy)
  ].filter(Boolean)
  return parts.join(' · ')
})

onMounted(() => {
  expireTickTimer = setInterval(() => {
    nowTick.value = Date.now()
  }, 30 * 1000)
})

onBeforeUnmount(() => {
  if (expireTickTimer) {
    clearInterval(expireTickTimer)
    expireTickTimer = null
  }
})

function confirmDelete() {
  if (props.busy) return
  dialog.warning({
    title: t('common.confirm'),
    content: t('xai.deleteConfirm'),
    positiveText: t('common.ok'),
    negativeText: t('common.cancel'),
    onPositiveClick: () => {
      emit('delete', props.account.id || '')
    }
  })
}

function truncateToken(token?: string): string {
  if (!token || token.length <= 16) return token || ''
  return token.substring(0, 8) + '...' + token.substring(token.length - 8)
}

function truncateText(text: string | undefined, maxLength: number): string {
  if (!text || text.length <= maxLength) return text || ''
  return text.substring(0, maxLength) + '...'
}
</script>

<style scoped>
.xai-account-card {
  background: var(--bg-primary);
  border: 2px solid var(--border-color);
  border-radius: var(--radius-lg, 8px);
  padding: 10px 12px;
  transition: all 0.2s ease;
  display: flex;
  flex-direction: column;
  min-height: 0;
  position: relative;
  justify-content: space-between;
  gap: 6px;
}

.xai-account-card:hover {
  box-shadow: var(--shadow-md, 0 4px 12px rgba(0, 0, 0, 0.1));
}

.xai-account-card.active {
  border-color: var(--accent, #0284c7);
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.15);
}

.xai-account-card.banned {
  background: rgba(244, 67, 54, 0.05);
  border-color: rgba(244, 67, 54, 0.4);
}

.xai-account-card.banned:hover {
  box-shadow: 0 4px 12px rgba(244, 67, 54, 0.15);
}

.xai-account-card.cooldown {
  opacity: 0.7;
}

.xai-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 0;
}

.account-email {
  flex: 1;
  min-width: 0;
  font-weight: 600;
  font-size: 13px;
  color: var(--text-primary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  margin-right: 10px;
}

.card-tags {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 0;
  flex-wrap: wrap;
}

.xai-badge-active {
  margin-left: auto;
}

.card-body {
  margin-bottom: 0;
  flex: 0 0 auto;
}

.quota-info {
  font-size: 11px;
  color: var(--text-secondary, #536173);
  margin-top: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-variant-numeric: tabular-nums;
}

.proxy-info {
  font-size: 11px;
  color: var(--text-tertiary);
  margin-top: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.card-footer {
  margin-top: 4px;
  padding-top: 6px;
  border-top: 1px solid var(--border-color, #e0e0e0);
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 8px;
}

.expire-info {
  font-size: 12px;
  color: var(--text-tertiary);
}

.expire-info.expired {
  color: var(--danger, #dc2626);
  font-weight: 500;
}

.card-actions {
  margin-left: auto;
  display: inline-flex;
  align-items: center;
  border: 1px solid var(--border-color, #d5dee9);
  border-radius: 0;
  overflow: hidden;
  background: var(--bg-primary, #ffffff);
  flex-shrink: 0;
}

.xai-action-btn {
  appearance: none;
  border: 0;
  border-right: 1px solid var(--border-color, #d5dee9);
  border-radius: 0;
  background: transparent;
  color: var(--text-secondary, #536173);
  min-width: 32px;
  height: 28px;
  padding: 0;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.xai-action-btn:last-child {
  border-right: 0;
}

.xai-action-btn:hover:not(:disabled) {
  background: var(--bg-tertiary, #eef3f8);
  color: var(--text-primary, #1f2937);
}

.xai-action-btn:focus-visible {
  outline: 2px solid color-mix(in srgb, var(--accent, #0284c7) 35%, transparent);
  outline-offset: -2px;
}

.xai-action-btn:disabled {
  cursor: not-allowed;
  opacity: 0.45;
}

.xai-action-primary {
  color: var(--accent, #0284c7);
}

.xai-action-primary:hover:not(:disabled) {
  background: color-mix(in srgb, var(--accent, #0284c7) 10%, white);
}

.xai-action-danger {
  color: var(--danger, #dc2626);
}

.xai-action-danger:hover:not(:disabled) {
  background: color-mix(in srgb, var(--danger, #dc2626) 10%, white);
}

.xai-action-icon {
  width: 15px;
  height: 15px;
  flex-shrink: 0;
}
</style>
